
import pytest
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django.contrib.gis.geos import Point
from hydrology.models import IDFTable, TemporalPattern

User = get_user_model()


@pytest.mark.django_db
class TestIDFTableModel:

    def setup_method(self):
        self.user = User.objects.create(username='test_user')
        self.valid_data_inches = {
            "columnDefs": [
                {
                    "field": "duration",
                    "width": 100,
                    "pinned": "left",
                    "headerName": "Duration (min)",
                },
                {
                    "ari": 0.5,
                    "field": "0-5yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "0.5yr ARI",
                    "stakeholderLabel": "2 EY",
                },
                {
                    "ari": 1,
                    "field": "1yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "1yr ARI",
                    "stakeholderLabel": "1 EY",
                },
                {
                    "ari": 2,
                    "field": "2yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "2yr ARI",
                    "stakeholderLabel": "40% AEP",
                },
                {
                    "ari": 5,
                    "field": "5yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "5yr ARI",
                    "stakeholderLabel": "40% AEP",
                },
                {
                    "ari": 10,
                    "field": "10yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "10yr ARI",
                    "stakeholderLabel": "40% AEP",
                },
                {
                    "ari": 20,
                    "field": "20yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "20yr ARI",
                    "stakeholderLabel": "5% AEP",
                },
                {
                    "ari": 50,
                    "field": "50yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "50yr ARI",
                    "stakeholderLabel": "2% AEP",
                },
                {
                    "ari": 100,
                    "field": "100yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "100yr ARI",
                    "stakeholderLabel": "1% AEP",
                },
                {
                    "ari": 500,
                    "field": "500yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "500yr ARI",
                    "stakeholderLabel": "0.2% AEP",
                },
            ],
            "rowData": [
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 5,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 10,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": "127",
                    "5yrARI": 147.32,
                    "10yrARI": 159.51,
                    "20yrARI": 179.83,
                    "50yrARI": 194.06,
                    "0-5yrARI": 0,
                    "100yrARI": 207.26,
                    "500yrARI": 219.46,
                    "duration": 15,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 20,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 102.62,
                    "5yrARI": 128.02,
                    "10yrARI": 142.75,
                    "20yrARI": 160.02,
                    "50yrARI": 173.74,
                    "0-5yrARI": 0,
                    "100yrARI": 187.96,
                    "500yrARI": 201.68,
                    "duration": 30,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 45,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 60,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 120,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 180,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 240,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 300,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 360,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 540,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 720,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 900,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 1080,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 6.16,
                    "5yrARI": 7.79,
                    "10yrARI": 8.95,
                    "20yrARI": 10.5,
                    "50yrARI": 11.75,
                    "0-5yrARI": 0,
                    "100yrARI": 12.91,
                    "500yrARI": 14.09,
                    "duration": 1440,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 2880,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 2.27,
                    "5yrARI": 2.96,
                    "10yrARI": 3.52,
                    "20yrARI": 4.06,
                    "50yrARI": 4.55,
                    "0-5yrARI": 0,
                    "100yrARI": 5.05,
                    "500yrARI": 5.56,
                    "duration": 4320,
                },
            ],
        }
        self.valid_data_mm = {
            "columnDefs": [
                {
                    "field": "duration",
                    "width": 100,
                    "pinned": "left",
                    "headerName": "Duration (min)",
                },
                {
                    "ari": 0.5,
                    "field": "0-5yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "0.5yr ARI",
                    "stakeholderLabel": "2 EY",
                },
                {
                    "ari": 1,
                    "field": "1yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "1yr ARI",
                    "stakeholderLabel": "1 EY",
                },
                {
                    "ari": 2,
                    "field": "2yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "2yr ARI",
                    "stakeholderLabel": "40% AEP",
                },
                {
                    "ari": 5,
                    "field": "5yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "5yr ARI",
                    "stakeholderLabel": "40% AEP",
                },
                {
                    "ari": 10,
                    "field": "10yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "10yr ARI",
                    "stakeholderLabel": "40% AEP",
                },
                {
                    "ari": 20,
                    "field": "20yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "20yr ARI",
                    "stakeholderLabel": "5% AEP",
                },
                {
                    "ari": 50,
                    "field": "50yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "50yr ARI",
                    "stakeholderLabel": "2% AEP",
                },
                {
                    "ari": 100,
                    "field": "100yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "100yr ARI",
                    "stakeholderLabel": "1% AEP",
                },
                {
                    "ari": 500,
                    "field": "500yrARI",
                    "width": 60,
                    "editable": True,
                    "headerName": "500yr ARI",
                    "stakeholderLabel": "0.2% AEP",
                },
            ],
            "rowData": [
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 5,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 10,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": "127",
                    "5yrARI": 147.32,
                    "10yrARI": 159.51,
                    "20yrARI": 179.83,
                    "50yrARI": 194.06,
                    "0-5yrARI": 0,
                    "100yrARI": 207.26,
                    "500yrARI": 219.46,
                    "duration": 15,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 20,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 102.62,
                    "5yrARI": 128.02,
                    "10yrARI": 142.75,
                    "20yrARI": 160.02,
                    "50yrARI": 173.74,
                    "0-5yrARI": 0,
                    "100yrARI": 187.96,
                    "500yrARI": 201.68,
                    "duration": 30,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 45,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 60,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 120,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 180,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 240,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 300,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 360,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 540,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 720,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 900,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 1080,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 6.16,
                    "5yrARI": 7.79,
                    "10yrARI": 8.95,
                    "20yrARI": 10.5,
                    "50yrARI": 11.75,
                    "0-5yrARI": 0,
                    "100yrARI": 12.91,
                    "500yrARI": 14.09,
                    "duration": 1440,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 0,
                    "5yrARI": 0,
                    "10yrARI": 0,
                    "20yrARI": 0,
                    "50yrARI": 0,
                    "0-5yrARI": 0,
                    "100yrARI": 0,
                    "500yrARI": 0,
                    "duration": 2880,
                },
                {
                    "1yrARI": 0,
                    "2yrARI": 2.27,
                    "5yrARI": 2.96,
                    "10yrARI": 3.52,
                    "20yrARI": 4.06,
                    "50yrARI": 4.55,
                    "0-5yrARI": 0,
                    "100yrARI": 5.05,
                    "500yrARI": 5.56,
                    "duration": 4320,
                },
            ],
        }
        self.latitude = 40.0308
        self.longitude = -88.5889

    def test_valid_cumulative_data_in_inches(self):
        idf_table = IDFTable.objects.create(
            created_by=self.user,
            name='Test Location',
            location_geom=Point(self.longitude, self.latitude),
            source='Test Source',
            description='Test note',
            data=self.valid_data_inches
        )
        for label, frequency in idf_table.frequencies.items():
            assert frequency == self.valid_data_mm.get(label)

    def test_valid_cumulative_data_in_millimeters(self):
        idf_table = IDFTable.objects.create(
            created_by=self.user,
            name='Test Location',
            location_geom=Point(self.longitude, self.latitude),
            source='Test Source',
            description='Test note',
            data=self.valid_data_mm
        )
        for label, frequency in idf_table.frequencies.items():
            assert frequency == self.valid_data_mm.get(label)

    def test_invalid_jsonfields_different_lengths_raises_error(self):
        # Alter one of the lists to make it a different length
        invalid_data = self.valid_data_inches.copy()
        invalid_data['rowData'] = [1, 2, 3]

        with pytest.raises(ValidationError):
            idf_table = IDFTable.objects.create(
                created_by=self.user,
                name='Invalid Test Location',
                location_geom=Point(self.longitude, self.latitude),
                source='Invalid Test Source',
                description='Invalid test note',
                data=invalid_data
            )

    def test_invalid_jsonfields_not_list_raises_error(self):
        invalid_data = self.valid_data_inches.copy()
        invalid_data['rowData'] = "not a list"

        with pytest.raises(ValidationError):
            idf_table = IDFTable.objects.create(
                created_by=self.user,
                name='Another Invalid Test Location',
                location_geom=Point(self.longitude, self.latitude),
                source='Another Invalid Test Source',
                description='Another invalid test note',
                data=invalid_data
            )

    @pytest.mark.parametrize("aep, expected_ari", [
        (62.3, 1),
        (50, 1.44),
        (10, 10),
        (1, 100),
        (0.1, 1000),
    ])
    def test_ari_from_aep(self, aep, expected_ari):
        assert pytest.approx(IDFTable.ari_from_aep(aep), 0.1) == expected_ari

    @pytest.mark.parametrize("ari, expected_aep", [
        (1, 62.3),
        (2, 40),
        (10, 10),
        (25, 4),
        (100, 1),
        (1000, 0.1)
    ])
    def test_aep_from_ari(self, ari, expected_aep):
        assert pytest.approx(IDFTable.aep_from_ari(ari), 0.1) == expected_aep

    @pytest.mark.skip
    def test_create_timeseries_from_idftable(self):
        expected_timeseries = [
            {"ts": "1970-01-01T00:00:00+00:00", "value": 5.4864},
            {"ts": "1970-01-01T00:07:30+00:00", "value": 1.09728},
            {"ts": "1970-01-01T00:15:00+00:00", "value": 9.87552},
            {"ts": "1970-01-01T00:22:30+00:00", "value": 18.653760000000002},
            {"ts": "1970-01-01T00:30:00+00:00", "value": 6.0350399999999995},
            {"ts": "1970-01-01T00:37:30+00:00", "value": 2.7432},
            {"ts": "1970-01-01T00:45:00+00:00", "value": 6.583679999999999},
            {"ts": "1970-01-01T00:52:30+00:00", "value": 4.38912},
            {"ts": "1970-01-01T01:00:00+00:00", "value": 4.38912},
        ]

        idf_table = IDFTable.objects.create(
            created_by=self.user,
            name='Test Location',
            location_geom=Point(self.longitude, self.latitude),
            source='Test Source',
            description='Test note',
            **self.valid_data_mm
        )
        duration = 60
        frequency = 'percent_10'
        temporal_pattern_list = [0.10, 0.02, 0.18, 0.34, 0.11, 0.05, 0.12, 0.08,]
        temporal_pattern = TemporalPattern.objects.create(
            pattern=temporal_pattern_list,
            name="TestPattern",
            source="Imaginary test data"
        )
        timeseries = idf_table.create_timeseries(duration, frequency, temporal_pattern, user=None)
        assert timeseries.data == expected_timeseries

    def test_selected_frequencies_and_durations(self):
        pass
