# Generated by Django 3.2.20 on 2024-04-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0002_auto_20240404_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='idftable',
            name='percent_4',
            field=models.JSONField(blank=True, null=True, verbose_name='4%'),
        ),
    ]
