# Generated by Django 3.2.20 on 2024-04-04 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydrology', '0003_idftable_percent_4'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=500)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pattern', models.JSONField(blank=True, null=True, verbose_name='Pattern')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_pattern_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_pattern_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Temporal Pattern',
                'verbose_name_plural': 'Temporal Patterns',
            },
        ),
    ]
