# Generated by Django 3.2.20 on 2024-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0004_temporalpattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='name',
            field=models.CharField(default='default_name', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeseries',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
