# Generated by Django 3.2.20 on 2024-04-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0005_auto_20240404_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='data',
            field=models.JSONField(default=[]),
        ),
    ]
