# Generated by Django 3.2.20 on 2024-04-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0006_alter_timeseries_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='idftable',
            name='conversion_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idftable',
            name='original_units',
            field=models.CharField(choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('in', 'Inches')], default='mm', max_length=4),
        ),
        migrations.AddField(
            model_name='idftable',
            name='saved_units',
            field=models.CharField(choices=[('mm', 'Millimeters'), ('cm', 'Centimeters'), ('in', 'Inches')], default='mm', max_length=4),
        ),
    ]
