# Generated by Django 3.2.20 on 2024-04-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0007_auto_20240405_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='data',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
