# Generated by Django 3.2.20 on 2024-04-06 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gn_anuga', '0080_useragreement'),
        ('hydrology', '0009_auto_20240405_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='idftable',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idf_table_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='idftable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gn_anuga.project'),
        ),
        migrations.AddField(
            model_name='idftable',
            name='selected_durations',
            field=models.JSONField(blank=True, null=True, verbose_name='Selected Durations'),
        ),
        migrations.AddField(
            model_name='idftable',
            name='selected_frequencies',
            field=models.JSONField(blank=True, null=True, verbose_name='Selected Frequencies'),
        ),
        migrations.AddField(
            model_name='temporalpattern',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporal_pattern_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='temporalpattern',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gn_anuga.project'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeseries_owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gn_anuga.project'),
        ),
    ]
