# Generated by Django 3.2.20 on 2024-05-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gn_anuga', '0082_auto_20240506_0709'),
        ('hydrology', '0010_auto_20240408_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='idftable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gn_anuga.project'),
        ),
        migrations.AddField(
            model_name='temporalpattern',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gn_anuga.project'),
        ),
        migrations.AddField(
            model_name='timeseries',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gn_anuga.project'),
        ),
    ]
