# Generated by Django 3.2.20 on 2024-05-17 13:59

from django.db import migrations, models
import gn_anuga.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0012_auto_20240517_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='chart',
            field=models.ImageField(blank=True, null=True, storage=gn_anuga.storage_backends.AnugaDataStorage(), upload_to='timeseries/chart/'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='data',
            field=models.FileField(blank=True, null=True, storage=gn_anuga.storage_backends.AnugaDataStorage(), upload_to='timeseries/data/'),
        ),
    ]
