# Generated by Django 3.2.20 on 2024-05-18 07:49

from django.db import migrations, models
import gn_anuga.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0013_auto_20240517_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeseries',
            name='stac',
            field=models.FileField(blank=True, null=True, storage=gn_anuga.storage_backends.AnugaDataStorage(), upload_to='timeseries/stac/'),
        ),
        migrations.AlterField(
            model_name='timeseries',
            name='data',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
