# Generated by Django 3.2.20 on 2024-05-23 09:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0015_rename_location_name_idftable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idftable',
            name='location_geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='idftable',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='temporalpattern',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
