# Generated by Django 3.2.20 on 2024-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0016_auto_20240523_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idftable',
            name='chart',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='durations_in_mins',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_0_2',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_0_5',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_1',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_12',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_2',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_3',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_4',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='ey_6',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_0_002',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_0_01',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_0_05',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_0_2',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_0_5',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_1',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_10',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_2',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_20',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_4',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_5',
        ),
        migrations.RemoveField(
            model_name='idftable',
            name='percent_50',
        ),
        migrations.AddField(
            model_name='idftable',
            name='data',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
