# Generated by Django 3.2.20 on 2024-05-24 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0017_auto_20240524_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idftable',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='temporalpattern',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='timeseries',
            old_name='notes',
            new_name='description',
        ),
    ]
