# Generated by Django 3.2.20 on 2024-05-24 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0018_auto_20240524_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporalpattern',
            old_name='pattern',
            new_name='data',
        ),
    ]
