# Generated by Django 3.2.20 on 2024-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrology', '0019_rename_pattern_temporalpattern_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idftable',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
