name: pytest-hydrology

on:
  push:
    branches: [ main, 4.1.x ]
  pull_request:
    branches: [ main, 4.1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install gdal-bin libgdal-dev
        python -m pip install --upgrade pip
        pip install GDAL==`gdal-config --version`
        pip install -r requirements_test.txt

    - name: Run Tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/github_actions
      run: |
        pip install pytest-django
        python -m pytest