name: pytest-hydrology

on:
  push:
    branches: [ main, 4.1.x ]
  pull_request:
    branches: [ main, 4.1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: test_database_user
          POSTGRES_PASSWORD: test_database_password
          POSTGRES_DB: test_database_name
        ports:
          - 5433:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        pip install pytest-django
        python -m pytest